# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True, verbose_name='Date subscribed')),
            ],
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='subscriber',
            field=models.ManyToManyField(to='mailinglist.Subscriber'),
        ),
    ]
